spring:
#  datasource:
#    url: jdbc:postgresql://dbm:5432/smarthomeman
#    username: me
#    password: 123
#    driverClassName: org.postgresql.Driver
#    hikari:
#      allow-pool-suspension: true
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    properties:
#      hibernate:
#        boot.allow_jdbc_metadata_access: false
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:entities.sql

#server:
#  port: 8000
quarkus:
  http:
    port: 8000
    access-log.enabled: true
    auth.proactive: false
  oidc:
    application-type: service